name: setup_node_and_install_dependencies
description: Setup Node, install Pnpm, and install dependencies.
inputs:
  node-version:
    required: false
    description: The version of Node to use.
    default: '22.x'
runs:
  using: 'composite'
  steps:
    - name: Setup Node and Pnpm
      uses: ./.github/actions/setup-node
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install
      run: pnpm i
      shell: bash
