name: setup_node
description: Setup Node, and install Pnpm
inputs:
  node-version:
    required: false
    description: The version of Node to use.
    default: '22.x'
runs:
  using: 'composite'
  steps:
    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        registry-url: 'https://registry.npmjs.org'
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install
      run: pnpm i
      shell: bash
