tasks:
  - name: Setup and Build
    init: |
      pnpm install
      pnpm run build
vscode:
  extensions:
    - streetsidesoftware.code-spell-checker
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false
