---

# For use with pre-commit.
# See usage instructions at http://pre-commit.com

-   id: cspell
    name: cspell
    description: This hook runs cspell spellchecker
    entry: cspell
    language: node
    types: [file]
    verbose: true
