---
packages:
  - 'packages/*'
  - 'packages/*/scripts'
  - 'packages/*/example-code'
  - 'packages/cspell-eslint-plugin/fixtures/dictionaries'
  - 'packages/cspell-eslint-plugin/fixtures/import-support'
  - 'packages/cspell-eslint-plugin/fixtures/issue-8261'
  - 'packages/cspell-eslint-plugin/fixtures/simple'
  - 'rfc/*'
  - 'rfc/drafts/*'
  - 'test-fixtures/dictionaries/*'
  - 'test-fixtures/issues/issue-5034'
  - 'test-fixtures/issues/issue-5034/frontend'
  - 'test-packages/*/*'
  - 'test-packages/*/*/bin'
  - 'test-packages/*/*/source'
  - 'test-packages/yarn'
  - 'tools/*'
  - doc-generator
  - examples/*
  - integration-tests
  - scripts
  - website
  - website/_scripts

overrides:
  'iconv-lite@0.7.1': '0.7.0' # See: https://github.com/pillarjs/iconv-lite/issues/363
