---
packages:
  - 'packages/*'
  - 'packages/*/scripts'
  - 'packages/cspell-eslint-plugin/fixtures/import-support'
  - 'packages/cspell-eslint-plugin/fixtures/simple'
  - 'rfc/*'
  - 'rfc/drafts/*'
  - 'test-fixtures/dictionaries/*'
  - 'test-fixtures/issues/issue-5034'
  - 'test-fixtures/issues/issue-5034/frontend'
  - 'test-packages/*/*'
  - 'test-packages/*/*/bin'
  - 'test-packages/*/*/source'
  - 'test-packages/yarn'
  - 'tools/*'
  - doc-generator
  - examples/*
  - integration-tests
  - scripts
  - website
