---
packages:
  - "packages/*"
  - "rfc/*"
  - "test-packages/*/*"
  - "test-packages/*/*/bin"
  - "test-packages/*/*/source"
  - "test-fixtures/issues/issue-5034"
  - "test-fixtures/issues/issue-5034/frontend"
  - doc-generator
  - integration-tests
  - scripts
  - website
