---
packages:
  - '@internal/*'
  - 'packages/*'
  - 'packages/*/scripts'
  - 'packages/*/example-code'
  - 'packages/cspell-eslint-plugin/fixtures/dictionaries'
  - 'packages/cspell-eslint-plugin/fixtures/import-support'
  - 'packages/cspell-eslint-plugin/fixtures/issue-8261'
  - 'packages/cspell-eslint-plugin/fixtures/simple'
  - 'rfc/*'
  - 'rfc/drafts/*'
  - 'test-fixtures/dictionaries/*'
  - 'test-fixtures/issues/issue-5034'
  - 'test-fixtures/issues/issue-5034/frontend'
  - 'test-packages'
  - 'test-packages/*/*'
  - 'test-packages/*/*/bin'
  - 'test-packages/*/*/source'
  - 'test-packages/yarn'
  - 'tools/*'
  - 'fixtures/Samples'
  - examples/*
  - integration-tests
  - scripts
  - website
  - website/_scripts

overrides:
  'webpackbar@=6.0.1': '^7.0.0'
  '@isaacs/brace-expansion@=5.0.0': '^5.0.1'
  'diff@=7.0.0': '^8.0.3'

minimumReleaseAge: 2880 # two days
minimumReleaseAgeExclude:
  - '@cspell/dict-*'
blockExoticSubdeps: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@5.7.2
  - semver@6.3.1
  - undici-types@6.21.0

allowBuilds:
  '@parcel/watcher': false
  '@swc/core': true
  core-js: false
  esbuild: true
  skia-canvas: false
  unrs-resolver: true

# cspell:dictionaries npm
# cspell:ignore webpackbar unrs
