---
packages:
  - 'packages/*'
  - 'packages/*/scripts'
  - 'rfc/*'
  - 'test-fixtures/dictionaries/*'
  - 'test-fixtures/issues/issue-5034'
  - 'test-fixtures/issues/issue-5034/frontend'
  - 'test-packages/*/*'
  - 'test-packages/*/*/bin'
  - 'test-packages/*/*/source'
  - 'tools/*'
  - doc-generator
  - examples/dynamic-dictionaries
  - integration-tests
  - scripts
  - website
