name: Bug Report Form
description: Create a report to help us improve
title: "[Bug]: "
labels: ["Needs Investigating", "bug", "new issue"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!

        ## Information

  - type: checkboxes
    id: kind_of_issue
    attributes:
      label: Kind of Issue
      description: What type of issues are you having
      options:
        - label: "Runtime - command-line tools"
        - label: "Building / Compiling"
        - label: "Security"
        - label: "Change in behavior or regression."
        - label: "Crash / Error"

  - type: checkboxes
    id: component
    attributes:
      label: Tool or Library
      description: Which Tool or Library is causing the issue?
      options:
        - label: "**cspell** - the command-line spelling tool."
        - label: "**cspell/eslint-plugin** - the plugin for ESLint."
        - label: "**cspell-tools** - used for building dictionary files."
        - label: "**cspell-lib** - library that does the actual spell checking."
        - label: "**cspell-trie** - tool for working with trie files."
        - label: other

  - type: input
    id: cspell-version
    attributes:
      label: Version
      description: Which version of CSpell?
      placeholder: ex. 6.6.0
    validations:
      required: false

  - type: dropdown
    id: component-library
    attributes:
      label: Supporting Library
      description: Issue with supporting library?
      multiple: true
      options:
        - "Not sure"
        - "cspell-glob" # - library for matching glob patterns."
        - "cspell-io" # - thin file i/o library."
        - "cspell-trie-lib" # - trie lib."
        - "Other" # - one fo the other libraries."

  - type: dropdown
    id: os-type
    attributes:
      label: OS
      description: Which OS has the issue?
      multiple: true
      options:
        - "ALL"
        - "Macos"
        - "Linux"
        - "Windows"
        - "Other"
        - "N/A"

  - type: input
    id: on-version
    attributes:
      label: OS Version
      description: Which version of the OS?
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Bug Description

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what is happening.
      placeholder: Please tell us about the issue.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Description of the steps necessary to reproduce the behavior.
      placeholder: |
        1. Command line '...'
        2.
        3. Scroll down to '....'
        4. See error

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.

  - type: textarea
    id: more-info
    attributes:
      label: Additional Information
      description: Please provide any additional information that would help to understand the issue.
      value: |
        **Screenshots**

        If applicable, add screenshots to help explain your problem.

        **Additional context**

        Add any other context about the problem here.

        **`cspell.json`**

        If applicable, attach a copy of the `cspell.json` file.

        **Example Repository (Optional)**

        An example repository makes things easier to debug.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/streetsidesoftware/cspell/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
