name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["Needs Investigating", "bug", "new issue"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!

        ## Information

  - type: checkboxes
    id: kind_of_issue
    attributes:
      label: Kind of Issue
      description: What type of issues are you having
      options:
        - label: "Runtime - command-line tools"
        - label: "Building / Compiling"
        - label: "Security"
        - label: "Change in behavior or regression."
        - label: "Crash / Error"

  - type: checkboxes
    id: component
    attributes:
      label: Tool or Library
      description: Which Tool or Library is causing the issue?
      options:
        - label: "**cspell** - the command-line spelling tool."
        - label: "**cspell/eslint-plugin** - the plugin for ESLint."
        - label: "**cspell-tools** - used for building dictionary files."
        - label: "**cspell-lib** - library that does the actual spell checking."
        - label: "**cspell-trie** - tool for working with trie files."
        - label: other

  - type: input
    id: cspell-version
    attributes:
      label: Version
      description: Which version of CSpell?
      placeholder: ex. 6.6.0
    validations:
      required: false

  - type: dropdown
    id: component-library
    attributes:
      label: Supporting Library
      description: Issue with supporting library?
      multiple: true
      options:
        - "N/A"
        - "cspell-glob - library for matching glob patterns."
        - "cspell-io - thin file i/o library."
        - "cspell-trie-lib - trie lib."
        - "Other - one fo the other libraries."

  - type: checkboxes
    id: os-type
    attributes:
      label: OS
      description: Which OS has the issue?
      options:
        - label: "**ALL**"
        - label: "Macos"
        - label: "Linux"
        - label: "Windows"
        - label: "Other"

  - type: input
    id: on-version
    attributes:
      label: OS Version
      description: Which version of the OS?
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Bug Description

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what is happening.
      placeholder: Please tell us about the issue.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
