blank_issues_enabled: false
contact_links:
  - name: Words that should be add/removed from a dictionary
    url: https://github.com/streetsidesoftware/cspell-dicts/issues
    about: Please suggest corrections there.
