name: Feature Request
description: Suggest an idea for this project.
title: "💡: "
labels: ["enhancement", "new issue"]
body:
  - type: markdown
    attributes:
      value: |
        🛑✋ This is a feature request for cspell software. To add or remove words in a dictionary, visit [cspell-dicts](https://github.com/streetsidesoftware/cspell-dicts/issues).

        Thank you for taking the time to fill out this feature request! Please describe your request in as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: |
        Is your feature request related to a problem? Please give a clear and concise description of what the problem is.
      placeholder: I'm always frustrated when ...

  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: |
        Describe the solution you'd like. Give a clear and concise description of what you want to happen.
      placeholder: I suggest that ...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: |
        Give a clear and concise description of any alternative solutions or features you've considered.
      placeholder: Describe alternatives you've considered.

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: |
        Add any other context or screenshots about the feature request here.
      placeholder: Paste screenshots from your clipboard to upload them.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: >
        By submitting this feature request, you agree to follow our
        [Code of Conduct](https://github.com/streetsidesoftware/cspell/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
