// This file is generated by tools/patch-version.mjs

export { pkgDir } from './dirname.js';

export interface PackageJson {
    name: string;
    version: string;
    engines: { node: string };
}

export const name: string = 'cspell';
export const version: string = '10.0.0';
export const engines: PackageJson['engines'] = { node: '>=22.18.0' };

export const npmPackage: PackageJson = { name, version, engines };
