ignorePaths:
  - cspell*.{yaml,json}
ignoreWords:
  - todos
words:
  - estree
  - pnpm
  - synckit
  - treeshake
  - tsbuildinfo
flagWords:
  - blacklist->denylist
  - whitelist->allowlist
  - cafe->café
  - bluelist->greenList
  - Bluelist->GreenList
