# This config file can be used before `.svelte` support is added.
enableFiletypes:
  - svelte
languageSettings:
  - caseSensitive: false
    languageId: svelte
    dictionaries: ['typescript', 'npm', 'html', 'html-symbol-entities', 'css', 'fonts']
overrides:
  - filename: '**/*.svelte'
    languageId: svelte
