// Using old-style of `type` exports because the new style breaks some integrations.
export type { CSpellUserSettingsFields } from './configFields.js';
export { ConfigFields } from './configFields.js';
export type {
    CSpellReporter,
    CSpellReporterModule,
    DebugEmitter,
    ErrorEmitter,
    ErrorLike,
    Issue,
    MessageEmitter,
    MessageType,
    MessageTypeLookup,
    ProgressBase,
    ProgressEmitter,
    ProgressFileBase,
    ProgressFileBegin,
    ProgressFileComplete,
    ProgressItem,
    ProgressTypes,
    ResultEmitter,
    RunResult,
    SpellingErrorEmitter,
} from './CSpellReporter.js';
export { IssueType, MessageTypes } from './CSpellReporter.js';
export type {
    AdvancedCSpellSettings,
    AdvancedCSpellSettingsWithSourceTrace,
    BaseSetting,
    CacheFormat,
    CacheSettings,
    CacheStrategy,
    CommandLineSettings,
    CSpellPackageSettings,
    CSpellSettings,
    CSpellSettingsWithSourceTrace,
    CSpellUserSettings,
    CSpellUserSettingsWithComments,
    ExperimentalBaseSettings,
    ExperimentalFileSettings,
    ExtendableSettings,
    FileSettings,
    FileSource,
    FsPath,
    FSPathResolvable,
    Glob,
    GlobDef,
    ImportFileRef,
    InMemorySource,
    LanguageId,
    LanguageIdMultiple,
    LanguageIdMultipleNeg,
    LanguageIdSingle,
    LanguageSetting,
    LanguageSettingFilterFields,
    LanguageSettingFilterFieldsDeprecated,
    LanguageSettingFilterFieldsPreferred,
    LegacySettings,
    LocaleId,
    LocalId,
    MergeSource,
    OverrideFilterFields,
    OverrideSettings,
    Pattern,
    PatternId,
    PatternRef,
    Plugin,
    PnPSettings,
    PredefinedPatterns,
    RegExpPatternDefinition,
    RegExpPatternList,
    ReporterSettings,
    ReportingConfiguration,
    Settings,
    SimpleGlob,
    Source,
    SuggestionsConfiguration,
    TrustLevel,
    Version,
    VersionLatest,
    VersionLegacy,
    WorkspaceTrustSettings,
} from './CSpellSettingsDef.js';
export type {
    CustomDictionaryPath,
    CustomDictionaryScope,
    DictionaryDefinition,
    DictionaryDefinitionAlternate,
    DictionaryDefinitionAugmented,
    DictionaryDefinitionBase,
    DictionaryDefinitionCustom,
    DictionaryDefinitionLegacy,
    DictionaryDefinitionPreferred,
    DictionaryFileTypes,
    DictionaryId,
    DictionaryNegRef,
    DictionaryPath,
    DictionaryRef,
    DictionaryReference,
    ReplaceEntry,
    ReplaceMap,
} from './DictionaryDefinition.js';
export type { CharacterSet, CharacterSetCosts, DictionaryInformation, EditCosts } from './DictionaryInformation.js';
export type { Feature, Features } from './features.js';
export type { ParsedText, Parser, ParseResult, ParserName, ParserOptions } from './Parser/index.js';
export type { SuggestionCostMapDef, SuggestionCostsDefs } from './suggestionCostsDef.js';
export type { MappedText } from './TextMap.js';
export type { TextDocumentOffset, TextOffset } from './TextOffset.js';
