---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
languageSettings:
  - languageId: # if the file type matches
      - javascript
      - dockerfile
      - yaml
    # apply settings
    caseSensitive: false
