---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
dictionaryDefinitions:
  - name: project-words
    path: "./project-words.txt"
    addWords: true # Allow people to add words to this dictionary.
  - name: ignore-words
    path: "./ignore-words.txt"
    description: We should not suggest these word.
    noSuggest: true
dictionaries:
  - project-words
  - ignore-words
