import:
  - ../../cspell.yaml
words:
  - autofix
  - autofixes
  - autofixer
  - autofixed
  - autofixable
  - autofixing
  - backreferences
  - backreference
  - builtins
  - camelcase
  - camelcased
  - checkstyle
  - classname
  - codebase
  - codebases
  - codeframe
  - dosomething
  - doublecircle
  - doublequote
  - eqeqeq
  - eslintconfig
  - eslintplugin
  - eslintignore
  - espree
  - escope
  - esquery
  - eslintrc
  - eslintrcjson
  - eslintrcyaml
  - eslintrcjs
  - eslintrcjson
  - eslintrcyaml
  - eslintrcjs
  - fileoverview
  - fillcolor
  - fixedsize
  - fixedmode
  - gitignores
  - globalstrict
  - hashbang
  - hashbangs
  - iife
  - iifes
  - imurmurhash
  - instanceof
  - linebreak
  - linebreaks
  - autocrlf
  - concat
  - hiddenfolder
  - hola
  - lookaround
  - lookbehinds
  - multipass
  - parenthesised
  - pluggable
  - postprocess
  - postprocessed
  - preprocess
  - redeclaration
  - redeclarations
  - redeclared
  - regexpp
  - rulesdir
  - rulesdirs
  - singlequote
  - testcase
  - testcases
  - testsuite
  - testsuites
  - typedefs
  - unignore
  - unignored
  - unignores
  - unparenthesized
