// This file is generated by tools/patch-version.mjs

export { pkgDir } from './dirname.js';

export const name = 'cspell';
export const version = '9.1.2';
export const engines = { node: '>=20' };

export const npmPackage = { name, version, engines };
