// This file is generated by tools/patch-version.mjs

export { pkgDir } from './dirname.js';

export const name = 'cspell';
export const version = '8.12.1';
export const engines = { node: '>=18' };

export const npmPackage = { name, version, engines };
