$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
import:
  - ./cspell-reporter.json
  - ./temp//MicrosoftDocs/PowerShell-Docs/.vscode/cSpell.json
ignorePaths:
  - "*.mdb"
  - "*.json"
