ignorePaths:
  - "*.{ts,js}"
  - "cspell*.{json,yaml}"
ignoreWords:
  - quic
  - tsbuildinfo
words:
  - pnpm
flagWords:
  - blacklist->denylist
  - whitelist->allowlist
  - café->cafe
  - bluelist->greenList
  - Bluelist->GreenList
