name: autofix.ci
on:
  pull_request:
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  autofix:
    if: github.repository_owner == 'streetsidesoftware' && contains(github.actor, 'dependabot') != true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup and Build
        uses: ./.github/actions/install-build-cache
        with:
          node-version: 22.x

      - name: Lint
        run: pnpm run lint

      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
