name: Coverage
on:
  pull_request:
    paths:
      - "*.js"
      - "*.ts"
      - "package-lock.json"
      - "package.json"
      - "packages/**/*.js"
      - "packages/**/*.ts"
      - "packages/**/package-lock.json"
      - "packages/**/package.json"
      - ".github/workflows/coverage.yml"
      - "!docs/**"
  push:
    branches:
      - main
    paths:
      - "**/package.json"
      - "**/package-lock.json"
      - "**/*.ts"
      - "**/*.js"
      - ".github/workflows/coverage.yml"
      - "!docs/**"

permissions:
  contents: read

jobs:
  coverage:
    permissions:
      checks: write # for coverallsapp/github-action to create new checks
      contents: read # for actions/checkout to fetch code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3.1.1
        with:
          cache: npm

      - run: npm i -g npm@8
      - run: npm -v

      - name: Restore CSpell cache
        uses: actions/cache@v3
        with:
          key: cspell-cache-${{ runner.os }}-coverage-${{ hashFiles('**/*.ts', '**/*.md') }}
          path: |
            .cspell/.cspellcache
          restore-keys: |
            cspell-cache-${{ runner.os }}-coverage-
            cspell-cache-${{ runner.os }}-

      - run: npm ci
      - run: npm run build
      - run: npm run coverage

      - name: Upload coverage Coveralls
        uses: coverallsapp/github-action@9ba913c152ae4be1327bfb9085dc806cedb44057 # 1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@e3c560433a6cc60aec8812599b7844a7b4fa0d71 # v3
        with:
          directory: "."
          files: ./lcov.info
