name: cSpell TS/MD
on:
  pull_request:
    paths:
      - "**/*.ts"
      - "**/*.md"
      - ".github/workflows/cspell.yml"
  push:
    paths:
      - "**/*.ts"
      - "**/*.md"
      - ".github/workflows/cspell.yml"

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npx cspell "**/{*.ts,*.md}"
