name: ' 🛝 Release Drafter Labeler'

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_pr_labels:
    if: github.repository_owner == 'streetsidesoftware'
    permissions:
      pull-requests: write # for release-drafter/release-drafter to add label to PR
    runs-on: ubuntu-latest
    steps:
      - id: release-drafter-labeler
        uses: release-drafter/release-drafter/autolabeler@4d75298e00d9e34c483e5ff8c68d0ea1c1940c1e # v7.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# cspell:ignore auto* *labeler
