name: ' 🛝 Release Drafter Labeler'

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_pr_labels:
    if: github.repository_owner == 'streetsidesoftware'
    permissions:
      pull-requests: write # for release-drafter/release-drafter to add label to PR
    runs-on: ubuntu-latest
    steps:
      - id: release-drafter-labeler
        uses: release-drafter/release-drafter/autolabeler@693d20e7c1ce1a81d3a41962f85914253b518449 # v7.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# cspell:ignore auto* *labeler
