# Reusable Workflow
name: R - Build and Cache Dist

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Branch or hash
        required: false
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      patch:
        description: Optional patch to apply before building.
        required: false
        type: string
    outputs:
      key:
        description: Cache Key
        value: ${{ jobs.build.outputs.key }}
      path:
        description: Cache Path
        value: ${{ jobs.build.outputs.path }}
      ref:
        description: Ref Used
        value: ${{ jobs.build.outputs.ref }}

permissions:
  contents: read

env:
  RUNS_ON: ubuntu-latest
  NODE_VERSION: "16.x"
  NPM_VERSION: "8"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REF_BRANCH: ${{ inputs.ref || github.event.inputs.ref }}
    outputs:
      key: ${{ env.CACHE_KEY }}
      path: ${{ env.CACHE_PATH }}
      ref: ${{ env.REF_BRANCH }}
    steps:
      - name: Inputs
        env:
          INPUTS: ${{ toJSON(inputs || github.event.inputs) }}
        run: |
          echo "inputs: $INPUTS"

      - run: npm i -g npm@${{ env.NPM_VERSION }}
      - run: npm -v

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.REF_BRANCH }}

      - name: Patch
        if: ${{ inputs.patch }}
        env:
          PATCH: ${{ inputs.patch }}
        run: |
          echo "$PATCH" | git apply

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3.3.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            packages/*/package-lock.json
            integration-tests/package-lock.json

      - run: npm -v

      - name: Calc Key and Path
        id: key-and-path
        run: |
          echo "CACHE_PATH<<CACHE_PATH
          packages/*/dist
          integration-tests/dist
          CACHE_PATH" >> $GITHUB_ENV
          echo "CACHE_KEY=int-build-${{ hashFiles(
              'integration-tests/package-lock.json', 'integration-tests/src/**/*.ts', 'integration-tests/tsconfig.json',
              'packages/*/package-lock.json', 'packages/*/src/**/*.ts', 'packages/*/tsconfig.json'
            ) }}" >> $GITHUB_ENV

      - run: |
          echo key: ${{ env.CACHE_KEY }}
          echo "path: ${{ env.CACHE_PATH }}"

      - name: Cache Build
        id: step-cache-build
        uses: actions/cache@v3
        with:
          key: ${{ env.CACHE_KEY }}
          path: ${{ env.CACHE_PATH }}

      - name: Cached Results
        run: |
          echo Build Cache: ${{ steps.step-cache-build.outputs.cache-hit && 'Hit' || 'Miss' }}

      - name: Npm CI
        if: ${{ !steps.step-cache-build.outputs.cache-hit }}
        run: npm ci

      - name: Has Npm has failed?
        if: ${{ failure() }}
        run: |
          ls -alF /home/runner/.npm/_logs/*.log
          cat /home/runner/.npm/_logs/*.log

      - name: Build
        if: ${{ !steps.step-cache-build.outputs.cache-hit }}
        run: npm run build
