# Reusable Workflow
name: R - Build and Cache Dist

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Branch or hash
        required: false
      os:
        description: Operating System
        required: false
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        default: ubuntu-latest
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      patch:
        description: Optional patch to apply before building.
        required: false
        type: string
      os:
        description: Operating System
        required: false
        type: string
    outputs:
      key:
        description: Cache Key
        value: ${{ jobs.build.outputs.key }}
      path:
        description: Cache Path
        value: ${{ jobs.build.outputs.path }}
      ref:
        description: Ref Used
        value: ${{ jobs.build.outputs.ref }}

permissions:
  contents: read

env:
  NODE_VERSION: "16.x"
  NPM_VERSION: "8"

jobs:
  build:
    runs-on: ${{ inputs.os || 'ubuntu-latest' }}
    env:
      REF_BRANCH: ${{ inputs.ref || github.event.inputs.ref }}
    outputs:
      key: ${{ steps.calc-key.outputs.value }}
      path: ${{ steps.calc-path.outputs.value }}
      ref: ${{ env.REF_BRANCH }}
    steps:
      - name: Inputs
        env:
          INPUTS: ${{ toJSON(inputs || github.event.inputs) }}
        run: |
          echo "inputs: $INPUTS"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.REF_BRANCH }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Patch
        if: ${{ inputs.patch }}
        env:
          PATCH: ${{ inputs.patch }}
        run: |
          echo "$PATCH" | git apply

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - run: pnpm -v
      - run: pnpm i

      - id: calc-path
        uses: ./.github/actions/output
        with:
          value: |
            packages/*/dist
            integration-tests/dist
      - id: calc-key
        uses: ./.github/actions/output
        with:
          value: >-
            int-build-${{ hashFiles(
              'integration-tests/src/**/*.ts', 'integration-tests/tsconfig.json',
              '*-lock.yaml', 'packages/*/src/**/*.ts', 'packages/*/tsconfig.json'
            ) }}

      - run: |
          echo "key: ${{ steps.calc-key.outputs.value }}"
          echo "path: ${{ steps.calc-path.outputs.value }}"

      - name: Cache Build
        id: step-cache-build
        uses: actions/cache@v3
        with:
          key: ${{ steps.calc-key.outputs.value }}
          path: ${{ steps.calc-path.outputs.value }}

      - name: Cached Results
        run: |
          echo Build Cache: ${{ steps.step-cache-build.outputs.cache-hit && 'Hit' || 'Miss' }}

      - name: Pnpm CI
        if: ${{ !steps.step-cache-build.outputs.cache-hit }}
        run: pnpm i

      - name: Has Pnpm has failed?
        if: ${{ failure() }}
        run: |
          ls -alF /home/runner/.pnpm/_logs/*.log
          cat /home/runner/.pnpm/_logs/*.log

      - name: Build
        if: ${{ !steps.step-cache-build.outputs.cache-hit }}
        run: pnpm run build
