# Reusable Workflow
name: R - Build and Cache Dist

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Branch or hash
        required: false
      os:
        description: Operating System
        required: false
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        default: ubuntu-latest
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      patch:
        description: Optional patch to apply before building.
        required: false
        type: string
      os:
        description: Operating System
        required: false
        type: string
    outputs:
      key:
        description: Cache Key
        value: ${{ jobs.build.outputs.key }}
      path:
        description: Cache Path
        value: ${{ jobs.build.outputs.path }}
      ref:
        description: Ref Used
        value: ${{ jobs.build.outputs.ref }}

permissions:
  contents: read

env:
  NODE_VERSION: "16.x"
  NPM_VERSION: "8"

jobs:
  build:
    runs-on: ${{ inputs.os || 'ubuntu-latest' }}
    env:
      REF_BRANCH: ${{ inputs.ref || github.event.inputs.ref }}
    outputs:
      key: ${{ steps.build-and-cache.outputs.key }}
      path: ${{ steps.build-and-cache.outputs.path }}
      ref: ${{ env.REF_BRANCH }}
    steps:
      - name: Inputs
        env:
          INPUTS: ${{ toJSON(inputs || github.event.inputs) }}
        run: |
          echo "inputs: $INPUTS"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.REF_BRANCH }}

      - name: Pre-build and cache
        id: build-and-cache
        uses: ./.github/actions/build
        with:
          show-summary: true
          node-version: ${{ env.NODE_VERSION }}
          use-setup: true
