name: Test Debounce
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  debounce:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        run_num: [1, 2, 3, 4]

    outputs:
      ok: ${{ steps.debounce.outputs.ok }}
      block: ${{ steps.debounce.outputs.block }}

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/simple-debounce
        id: debounce
        with:
          tag: "test-debounce"
          debug: true
      - uses: ./.github/actions/echo
        with:
          value: ${{ toJSON(steps.debounce.outputs) }}

  debounce-result:
    needs:
      - debounce
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/echo
        with:
          value: |
            Needs: ${{ toJSON( needs ) }}
            Context: ${{ toJSON( job ) }}
            GitHub: ${{ toJSON( github) }}
